In [1]:
from __future__ import print_function
import torch

### Construct a 5x3 matrix, uninitialized: 

In [2]:
x = torch.empty(5, 3)

In [3]:
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8161e-42, 0.0000e+00],
        [0.0000e+00, 8.1356e+32, 0.0000e+00]])

### Construct a randomly initialized matrix

In [4]:
x = torch.rand(5, 3)
x

tensor([[0.6864, 0.1725, 0.3651],
        [0.8171, 0.7258, 0.6426],
        [0.4950, 0.8300, 0.7911],
        [0.4001, 0.4804, 0.3795],
        [0.1132, 0.2370, 0.4369]])

### Construct a matrix filled zeros and of data type long

In [5]:
x = torch.zeros(5, 3, dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### Construct a tensor directly from data 

In [6]:
x = torch.tensor([5.5, 3])

In [7]:
x

tensor([5.5000, 3.0000])

### Operations

In [12]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [13]:
x + y

tensor([[1.5420, 0.8893, 0.7037],
        [0.7559, 1.2152, 1.9165],
        [0.7570, 1.4469, 1.2040],
        [0.4504, 0.2245, 1.0056],
        [0.4971, 1.3654, 1.4815]])

In [14]:
torch.add(x, y)

tensor([[1.5420, 0.8893, 0.7037],
        [0.7559, 1.2152, 1.9165],
        [0.7570, 1.4469, 1.2040],
        [0.4504, 0.2245, 1.0056],
        [0.4971, 1.3654, 1.4815]])

In [ ]:
result