# PyTorch Basics

## Init, helpers, utils, ...

In [0]:
%matplotlib inline

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision

In [0]:
from pprint import pprint

import matplotlib.pyplot as plt
import numpy as np
from IPython.core.debugger import set_trace

# Tensors
tensors - the atoms of machine learning

## Tensors in numpy and pytorch

In [0]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [5]:
# numpy
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# torch
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [7]:
# numpy
X = np.random.random((5, 3))
X

array([[7.19241117e-01, 3.75315594e-01, 8.93115592e-01],
       [6.77972759e-01, 2.53235665e-01, 7.53947159e-01],
       [8.81000858e-02, 4.04645171e-01, 8.62199823e-01],
       [4.61886465e-01, 5.20938652e-04, 5.32576995e-01],
       [5.85370966e-01, 8.76073470e-01, 8.03249957e-01]])

In [8]:
# pytorch
Y = torch.rand((5, 3))
Y

tensor([[0.9095, 0.2711, 0.5523],
        [0.5015, 0.4351, 0.4668],
        [0.3769, 0.4143, 0.0880],
        [0.2388, 0.5465, 0.0327],
        [0.5563, 0.8945, 0.0480]])

In [9]:
X.shape

(5, 3)

In [10]:
Y.shape

torch.Size([5, 3])

In [11]:
# numpy
X.T @ X

array([[1.54071475, 0.99034715, 1.94567028],
       [0.99034715, 1.13623281, 1.57899493],
       [1.94567028, 1.57899493, 3.03832906]])

In [12]:
# torch
Y.t() @ Y

tensor([[1.5873, 1.2491, 0.8041],
        [1.2491, 1.5333, 0.4501],
        [0.8041, 0.4501, 0.5341]])

In [13]:
# numpy
inv(X.T @ X)

array([[ 3.4084902 ,  0.22463117, -2.29945125],
       [ 0.22463117,  3.18295046, -1.7980017 ],
       [-2.29945125, -1.7980017 ,  2.73604647]])

In [14]:
# torch
torch.inverse(Y.t() @ Y)

tensor([[ 10.6739,  -5.2854, -11.6159],
        [ -5.2854,   3.4837,   5.0215],
        [-11.6159,   5.0215,  15.1289]])

## More on PyTorch Tensors

Operations are also available as methods.

In [15]:
A = torch.eye(3)
A.add(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [0]:
A

Any operation that mutates a tensor in-place has a `_` suffix.

In [16]:
A.add_(1)
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

## Indexing and broadcasting
It works as expected/like numpy:

In [17]:
A[0, 0]

tensor(2.)

In [18]:
A[0]

tensor([2., 1., 1.])

In [19]:
A[0:2]

tensor([[2., 1., 1.],
        [1., 2., 1.]])

In [20]:
A[:, 1:3]

tensor([[1., 1.],
        [2., 1.],
        [1., 2.]])

## Converting

In [21]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
# torch --> numpy
B = A.numpy()
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

Note: torch and numpy can share the same memory / zero-copy

In [23]:
A.add_(.5)
A

tensor([[1.5000, 0.5000, 0.5000],
        [0.5000, 1.5000, 0.5000],
        [0.5000, 0.5000, 1.5000]])

In [24]:
B

array([[1.5, 0.5, 0.5],
       [0.5, 1.5, 0.5],
       [0.5, 0.5, 1.5]], dtype=float32)

In [25]:
# numpy --> torch
torch.from_numpy(np.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

## Much more

In [26]:
[o for o  in dir(torch) if not o.startswith("_")]

['AVG',
 'AggregationType',
 'Argument',
 'ArgumentSpec',
 'BFloat16Storage',
 'BFloat16Tensor',
 'BenchmarkConfig',
 'BenchmarkExecutionStats',
 'Block',
 'BoolStorage',
 'BoolTensor',
 'BoolType',
 'ByteStorage',
 'ByteTensor',
 'CharStorage',
 'CharTensor',
 'ClassType',
 'Code',
 'CompilationUnit',
 'CompleteArgumentSpec',
 'CudaBFloat16StorageBase',
 'CudaBoolStorageBase',
 'CudaByteStorageBase',
 'CudaCharStorageBase',
 'CudaDoubleStorageBase',
 'CudaFloatStorageBase',
 'CudaHalfStorageBase',
 'CudaIntStorageBase',
 'CudaLongStorageBase',
 'CudaShortStorageBase',
 'DictType',
 'DoubleStorage',
 'DoubleTensor',
 'ErrorReport',
 'ExecutionPlan',
 'ExtraFilesMap',
 'FatalError',
 'FileCheck',
 'FloatStorage',
 'FloatTensor',
 'FloatType',
 'Function',
 'FunctionSchema',
 'Future',
 'Generator',
 'Gradient',
 'Graph',
 'GraphExecutorState',
 'HalfStorage',
 'HalfStorageBase',
 'HalfTensor',
 'IODescriptor',
 'IntStorage',
 'IntTensor',
 'IntType',
 'JITException',
 'ListType',
 'Lock

In [27]:
[o for o  in dir(A) if not o.startswith("_")]

['T',
 'abs',
 'abs_',
 'acos',
 'acos_',
 'add',
 'add_',
 'addbmm',
 'addbmm_',
 'addcdiv',
 'addcdiv_',
 'addcmul',
 'addcmul_',
 'addmm',
 'addmm_',
 'addmv',
 'addmv_',
 'addr',
 'addr_',
 'all',
 'allclose',
 'any',
 'apply_',
 'argmax',
 'argmin',
 'argsort',
 'as_strided',
 'as_strided_',
 'asin',
 'asin_',
 'atan',
 'atan2',
 'atan2_',
 'atan_',
 'backward',
 'baddbmm',
 'baddbmm_',
 'bernoulli',
 'bernoulli_',
 'bfloat16',
 'bincount',
 'bitwise_not',
 'bitwise_not_',
 'bmm',
 'bool',
 'byte',
 'cauchy_',
 'ceil',
 'ceil_',
 'char',
 'cholesky',
 'cholesky_inverse',
 'cholesky_solve',
 'chunk',
 'clamp',
 'clamp_',
 'clamp_max',
 'clamp_max_',
 'clamp_min',
 'clamp_min_',
 'clone',
 'coalesce',
 'contiguous',
 'copy_',
 'cos',
 'cos_',
 'cosh',
 'cosh_',
 'cpu',
 'cross',
 'cuda',
 'cumprod',
 'cumsum',
 'data',
 'data_ptr',
 'dense_dim',
 'dequantize',
 'det',
 'detach',
 'detach_',
 'device',
 'diag',
 'diag_embed',
 'diagflat',
 'diagonal',
 'digamma',
 'digamma_',
 'dim',

# What about the GPU?
How do I use the GPU?

If you have a GPU make sure that the right pytorch is installed
(check https://pytorch.org/ for details).

In [28]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

If you have a GPU you should get something like: 
`device(type='cuda', index=0)`

You can move data to the GPU by doing `.to(device)`.

In [30]:
data = torch.eye(3)
data.to(device)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')

Now the computation happens on the GPU.

In [31]:
res = data + data
res

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [32]:
res.device

device(type='cpu')

Note: before `v0.4` one had to use `.cuda()` and `.cpu()` to move stuff to and from the GPU.
This littered the code with many:
```python
if CUDA:
    model = model.cuda()
```

# Automatic differentiation with `autograd`
Prior to `v0.4` PyTorch used the class `Variable` to record gradients. You had to wrap `Tensor`s in `Variable`s.
`Variable`s behaved exactly like `Tensors`.

With `v0.4` `Tensor` can record gradients directly if you tell it do do so, e.g. `torch.ones(3, requires_grad=True)`.
There is no need for `Variable` anymore.
Many tutorials still use `Variable`, be aware!

Ref:
- https://pytorch.org/docs/stable/autograd.html
- https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

You rarely use `torch.autograd` directly.
Pretty much everything is part or `torch.Tensor` now.
Simply add `requires_grad=True` to the tensors you want to calculate the gradients for.
`nn.Module` track gradients automatically.

In [0]:
from torch import autograd

In [34]:
x = torch.tensor(2.)
x

tensor(2.)

In [35]:
x = torch.tensor(2., requires_grad=True)
x

tensor(2., requires_grad=True)

In [0]:
print(x.requires_grad)

In [36]:
print(x.grad)

None


In [41]:
y = x ** 2

print("Grad of x:", x.grad)

Grad of x: None


In [43]:
# Don't record the gradient
# Useful for inference

params = torch.tensor(2., requires_grad=True)

with torch.no_grad():
    y = x * x
    print(x.grad_fn)

None


`nn.Module` and `nn.Parameter` keep track of gradients for you.

In [44]:
lin = nn.Linear(2, 1, bias=True)
lin.weight

Parameter containing:
tensor([[-0.7013,  0.6017]], requires_grad=True)

In [45]:
type(lin.weight)

torch.nn.parameter.Parameter

In [46]:
isinstance(lin.weight, torch.FloatTensor)

True