Lets look at array example with numpy that we already know.

In [1]:
# import numpy library
import numpy as np

In [2]:
array = [[1,2,3],[4,5,6]]
first_array = np.array(array) # 2x3 array

In [7]:
print("Array Type: {}".format(type(first_array))) # type

Array Type: <class 'numpy.ndarray'>


In [8]:
print("Array Shape: {}".format(np.shape(first_array))) # shape

Array Shape: (2, 3)


In [9]:
print(first_array)

[[1 2 3]
 [4 5 6]]


We looked at numpy array.
Now examine how we implement tensor(pytorch array)

In [10]:
# import pytorch library
import torch

In [12]:
tensor = torch.Tensor(array)   # array from the previous numpy part

In [13]:
print("Array Type: {}".format(tensor.type)) # type

Array Type: <built-in method type of Tensor object at 0x00000251770DE828>


In [14]:
print("Array Shape: {}".format(tensor.shape)) # shape

Array Shape: torch.Size([2, 3])


In [15]:
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


Ones

In [18]:
# numpy ones
print("Numpy \n {}".format(np.ones((2,3))))

Numpy 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# pytorch ones
print(torch.ones((2,3)))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


random

In [21]:
# numpy random
print("Numpy \n {}".format(np.random.rand(2,3)))

Numpy 
 [[0.29351679 0.68425945 0.34586502]
 [0.77422633 0.95699792 0.41140616]]


In [22]:
# pytorch random
print(torch.rand(2,3))

tensor([[0.5307, 0.0291, 0.1065],
        [0.7218, 0.4909, 0.7941]])


Basic Math with Pytorch

In [23]:
# create tensor 
tensor = torch.ones(3,3)
print("\n",tensor)


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [36]:
# Resize
print("{}{}\n".format(tensor.view(9).shape,tensor.view(9)))

torch.Size([9])tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])



In [42]:
tensor2 = torch.rand(3,3)
tensor2

tensor([[0.0655, 0.9494, 0.8999],
        [0.2151, 0.6481, 0.1844],
        [0.6678, 0.3319, 0.6158]])

In [41]:
# Addition
print("Addition: {}\n".format(torch.add(tensor,tensor2)))

Addition: tensor([[1.1527, 1.0598, 1.1362],
        [1.6866, 1.1317, 1.5675],
        [1.0725, 1.3367, 1.4445]])



In [45]:
# Subtraction
print("Subtraction: {}\n".format(tensor.sub(tensor2)))

Subtraction: tensor([[0.9345, 0.0506, 0.1001],
        [0.7849, 0.3519, 0.8156],
        [0.3322, 0.6681, 0.3842]])



In [47]:
# Element wise multiplication
print("Element wise multiplication: {}\n".format(torch.mul(tensor,tensor2)))

Element wise multiplication: tensor([[0.0655, 0.9494, 0.8999],
        [0.2151, 0.6481, 0.1844],
        [0.6678, 0.3319, 0.6158]])



In [48]:
# Element wise division
print("Element wise division: {}\n".format(torch.div(tensor,tensor2)))

Element wise division: tensor([[15.2780,  1.0533,  1.1113],
        [ 4.6498,  1.5430,  5.4223],
        [ 1.4974,  3.0127,  1.6240]])



In [50]:
# Mean
a = torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(a.mean()))

Mean: 3.0


In [52]:
# Standart deviation (std)
print("std: {}".format(a.std()))

std: 1.5811388492584229
