### 2.3.1 Element-wise operations

#### Naive python implementation of relu operation

In [13]:
import numpy as np


def naive_relu(x):     # x is a 2D numpy array
    assert len(x.shape) == 2
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j]=max(x[i,j],0)
    return x

xp = np.array([
    [5,78,45,9,48],
    [7,8,47,58,96],
    [84,79,2,5,48]
             ])
print(naive_relu(xp))


[[ 5 78 45  9 48]
 [ 7  8 47 58 96]
 [84 79  2  5 48]]
