In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.datasets import load_digits
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [24]:
digits = load_digits()


In [25]:
x_train, x_test, y_train, y_test = train_test_split(digits.data,
                                                    digits.target,
                                                    test_size = 0.3)

In [26]:
print(len(x_train)) # train data

1257


In [27]:
print(len(y_train)) # train labels

1257


In [28]:
print(len(x_test)) # test data

540


In [29]:
print(len(y_test)) # test labels

540


In [30]:
# model 1
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9648148148148148

In [31]:
# model 2
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.29814814814814816

In [33]:
# model 3
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(random_state=0)
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.8407407407407408

In [38]:
# model 4
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train, y_train)
neigh.score(x_test, y_test)

0.987037037037037

## Cross validation

In [39]:
from sklearn.model_selection import KFold

In [42]:
k = KFold(n_splits=5)
k

KFold(n_splits=4, random_state=None, shuffle=False)

In [44]:
for train_index, test_index in k.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)










[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]
