### Tensor axes example

In [1]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

Each element along the first axis, is an array:

In [2]:
dd[0]

[1, 2, 3]

In [3]:
dd[1]

[4, 5, 6]

In [4]:
dd[2]

[7, 8, 9]

Each element along the second axis, is a number:

In [5]:
dd[0][0]

1

In [7]:
dd[2][0]

7

In [8]:
import torch

In [9]:
t = torch.tensor(dd)

In [10]:
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
type(t)

torch.Tensor

In [12]:
t.shape

torch.Size([3, 3])

### Reshaping tensors

In [14]:
t.reshape(1, 9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
t.reshape(9, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])