In [1]:
import numpy as np

In [3]:
a = np.arange(10)

In [4]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [6]:
np.shares_memory(a,b)

True

In [7]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [8]:
a  # elements of a also changes cause they are sharing memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [13]:
# we can use copy() function to avoid sharing the memory
c = a[::2].copy()   # force
c


array([10,  2,  4,  6,  8])

In [14]:
np.shares_memory(a,c)

False

In [15]:
# Creating random numbers 
a = np.random.randint(0,20,10)  # 10 random numbers from 0 to 20
a

array([ 1,  0, 13,  4,  2,  9,  7, 18, 18,  7])

In [16]:
a_even = (a%2 ==0)
a_even

array([False,  True, False,  True,  True, False, False,  True,  True,
       False])

In [20]:
numbers_of_a = a[a_even]
numbers_of_a

array([ 0,  4,  2, 18, 18])

In [25]:
a[a_even] = -1 # Converting all even numbers to -1
a

array([ 1, -1, 13, -1, -1,  9,  7, -1, -1,  7])

In [27]:
arr = np.arange(0,100, 10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
arr[[1,6,9]]

array([10, 60, 90])

In [30]:
arr[[6,9]] = -100

In [31]:
arr

array([   0,   10,   20,   30,   40,   50, -100,   70,   80, -100])