In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [9]:
b = np.ones(10)+2
b

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [10]:
a-b

array([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])

In [11]:
d = np.diag([1,2,3,4])
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [12]:
d*d

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [15]:
# another way of doing matrix multiplicaton
d.dot(d)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [17]:
a = np.array([1,2,3,4])
b = np.array([1,2,8,4])
a == b  # element-wise comparision

array([ True,  True, False,  True])