In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [4]:
b = np.ones(10)+2
b

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [5]:
a-b

array([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])

In [6]:
d = np.diag([1,2,3,4])
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [7]:
d*d

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [8]:
# another way of doing matrix multiplicaton
d.dot(d)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [9]:
a = np.array([1,2,3,4])
b = np.array([1,2,8,4])
a == b  # element-wise comparision

array([ True,  True, False,  True])

In [10]:
 a > b

array([False, False, False, False])

In [11]:
a < b

array([False, False,  True, False])

In [12]:
np.array_equal(a,b)

False

In [14]:
np.logical_and(a,b)

array([ True,  True,  True,  True])

In [15]:
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [18]:
a = np.arange(5)

In [19]:
a

array([0, 1, 2, 3, 4])

In [21]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [22]:
np.log(a)

C:\Users\sadma\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [23]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])