In [1]:
import numpy as np
a = np.array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
a

array([1, 2, 3])

In [4]:
a.shape

(3,)

In [5]:
print(a[0],a[1],a[2])

1 2 3


In [6]:
a[0] = 5

In [7]:
a

array([5, 2, 3])

In [8]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
a = np.zeros((2,2))

In [11]:
a

array([[0., 0.],
       [0., 0.]])

In [12]:
b = np.ones((1,2))
b

array([[1., 1.]])

In [13]:
b = np.ones((5,2))

In [14]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
c = np.full((3,2), 7)
c

array([[7, 7],
       [7, 7],
       [7, 7]])

In [16]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [17]:
e = np.random.random((3,2)) 
print(e)

[[0.35156354 0.32383861]
 [0.24420166 0.82308693]
 [0.2058988  0.07726516]]


In [18]:
# array indexing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
b = a[2:, 2:4]
b

array([[11, 12]])

In [21]:
print(a[0, 1])

2


In [22]:
b[0, 0] = 77

In [23]:
b

array([[77, 12]])

In [24]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [25]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
row_r1 = a[1, :]

In [27]:
row_r1

array([5, 6, 7, 8])

In [28]:
row_r2 = a[1:2, :]
row_r2

array([[5, 6, 7, 8]])

In [29]:
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [30]:
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [31]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [32]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
b = np.array([0, 2, 0, 1])
b

array([0, 2, 0, 1])

In [34]:
print(a[np.arange(4), b])

[ 1  6  7 11]


In [35]:
b

array([0, 2, 0, 1])

In [36]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
L = range(1000)
%timeit [i**2 for i in L]

397 µs ± 16 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [38]:
a = np.arange(1000)
%timeit a**2

2.13 µs ± 283 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [39]:
# Creating arrays
a = np.array([0,1,2,5,6])
a

array([0, 1, 2, 5, 6])

In [40]:
a.ndim   # How much dimention it has?

1

In [41]:
a.shape   # How many elements are there? 

(5,)

In [42]:
len(a)  

5

In [43]:
# 2D arrays
two_d_arrays = np.array([[1,2,3],[4,5,6]])

In [44]:
two_d_arrays

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
two_d_arrays.ndim

2

In [46]:
two_d_arrays.shape

(2, 3)

In [47]:
len(two_d_arrays) # returns the size of the first dimension

2

In [48]:
three_d_ar = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [49]:
three_d_ar

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
three_d_ar.shape

(2, 2, 3)

In [51]:
three_d_ar.ndim

3

In [53]:
# creating complex datatype

a = np.array([1+2j,2+4j])

In [54]:
a

array([1.+2.j, 2.+4.j])

In [56]:
a.dtype   # data type

dtype('complex128')

In [57]:
string = np.array(['soumik','kabir','Sadman'])

In [58]:
string

array(['soumik', 'kabir', 'Sadman'], dtype='<U6')

In [59]:
string.dtype

dtype('<U6')