In [1]:
import numpy as np
a = np.array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
print(a[0],a[1],a[2])

1 2 3


In [7]:
a[0] = 5

In [8]:
a

array([5, 2, 3])

In [9]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.shape

(2, 3)

In [12]:
a = np.zeros((2,2))

In [13]:
a

array([[0., 0.],
       [0., 0.]])

In [14]:
b = np.ones((1,2))
b

array([[1., 1.]])

In [15]:
b = np.ones((5,2))

In [16]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
c = np.full((3,2), 7)
c

array([[7, 7],
       [7, 7],
       [7, 7]])

In [19]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [23]:
e = np.random.random((3,2)) 
print(e)

[[0.48901498 0.48767658]
 [0.25822205 0.80742395]
 [0.94749901 0.29686868]]


In [24]:
# array indexing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [25]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
b = a[2:, 2:4]
b

array([[11, 12]])

In [34]:
print(a[0, 1])

2


In [35]:
b[0, 0] = 77

In [36]:
b

array([[77, 12]])

In [37]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [38]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
row_r1 = a[1, :]

In [40]:
row_r1

array([5, 6, 7, 8])

In [41]:
row_r2 = a[1:2, :]
row_r2

array([[5, 6, 7, 8]])

In [42]:
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [43]:
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [44]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [45]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
b = np.array([0, 2, 0, 1])
b

array([0, 2, 0, 1])

In [47]:
print(a[np.arange(4), b])

[ 1  6  7 11]


In [48]:
b

array([0, 2, 0, 1])

In [49]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])