In [38]:
import numpy as np

In [46]:
a = np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
print("Array Shape =", a.shape)
print("Array Dimension =", a.ndim)

Array Shape = (100,)
Array Dimension = 1


### Reshaping and changing the array dimension

In [48]:
new_a = a.reshape(20, 5)   # 20*5 = 100

In [49]:
print("Array Shape =", new_a.shape)
print("Array Dimension =", new_a.ndim)

Array Shape = (20, 5)
Array Dimension = 2


### Calculate Euclidean distance between two points

In [25]:
a = np.array([1, 2, 3])  # point a
b = np.array([4, 5, 6])  # point b

dis = np.linalg.norm(a - b)
dis

5.196152422706632

In [27]:
"""
Using scipy:
We can also use scipy to calculate euclidean distance, though it's slower than np.linalg.norm
""" 
from scipy.spatial import distance

dst = distance.euclidean(a, b)
dst

5.196152422706632

### Return the indices that would sort an numpy array.

In [52]:
arr = np.array([1, 3, 2, 4, 5])
arr.argsort()

array([0, 2, 1, 3, 4], dtype=int64)

In [53]:
arr = np.array([1, 30, 2, 4, 5])   # # if ascending order
np.argsort(arr)

array([0, 2, 3, 4, 1], dtype=int64)

In [54]:
np.argsort(arr)[::-1]   # if descending order

array([1, 4, 3, 2, 0], dtype=int64)

### Access the ith column of a NumPy multidimensional array

In [56]:
test = np.array([[1, 2], [3, 4], [5, 6]])
test

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
i = 1  # 2nd column ; which contains elements: 2, 4, 6
test[:, i:]  # [row_Start: row_End, column_Start: column_End]

array([[2],
       [4],
       [6]])

In [62]:
# we can use flatten() function to flat the array
test[:, i:].flatten()

array([2, 4, 6])

### Convert a panda dataframe to numpy array

In [66]:
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3], 
                   'B': [4, 5, 6]}, 
                  index=['a', 'b', 'c']
                 )
df

A  B
a  1  4
b  2  5
c  3  6

#### Method: 1

In [67]:
np_df = df.values
np_df

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int64)

In [68]:
type(np_df)

numpy.ndarray

#### Method 2

In [69]:
df

A  B
a  1  4
b  2  5
c  3  6

In [70]:
np_df = df.to_numpy()
np_df

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int64)

In [71]:
type(np_df)

numpy.ndarray

#### Method 3

In [72]:
df

A  B
a  1  4
b  2  5
c  3  6

In [73]:
np_df = np.array(df)
np_df

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int64)

In [74]:
type(np_df)

numpy.ndarray

### Adding a new column to an existing dataframe which concate previous two columns

In [80]:
df = pd.DataFrame({'Year': ['2014', '2015'], 'Month': ['Jan', 'Feb']})
df

Year Month
0  2014   Jan
1  2015   Feb

In [81]:
# add a new column 'period'
df['period'] = df[['Year', 'Month']].apply(lambda x: ' - '.join(x), 
                                            axis=1)

In [82]:
df

Year Month      period
0  2014   Jan  2014 - Jan
1  2015   Feb  2015 - Feb