In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
a.shape

(2, 3)

In [4]:
a.shape = (3,2) # reshape the array

In [5]:
a.shape

(3, 2)

In [6]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# there is another function called reshape to reshape the array
ar = np.array([[4,5,6],[7,8,9]])

In [8]:
ar

array([[4, 5, 6],
       [7, 8, 9]])

In [9]:
ar.reshape(3,2)

array([[4, 5],
       [6, 7],
       [8, 9]])

In [11]:
# one dim array
a = np.arange(24)

In [12]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
a.ndim

1

In [16]:
b = a.reshape(2,4,3)

In [17]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [18]:
c = b.reshape(2,3,4)

In [19]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
c.ndim # what's the dimension

3

In [21]:
b.ndim

3

In [22]:
# returns the length of each element of array in bytes.
b.itemsize

4

In [23]:
x = np.zeros(5)

In [24]:
x

array([0., 0., 0., 0., 0.])

In [25]:
x = np.zeros(5,)

In [26]:
x

array([0., 0., 0., 0., 0.])

In [36]:
x = np.zeros((5), dtype = np.int)

In [37]:
x

array([0, 0, 0, 0, 0])

In [35]:
x

array([0, 0, 0, 0, 0])

In [39]:
z = np.zeros((2,2), dtype=int)

In [40]:
z

array([[0, 0],
       [0, 0]])

In [11]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


In [13]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)


{0: 0, 2: 4, 4: 16}


In [2]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])

cute


In [3]:
print(d['dog'])

furry


In [4]:
print('cat' in d)

True


In [5]:
d['fish'] = 'wet'

In [6]:
d

{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}

In [7]:
d = {'person': 2, 'cat': 4, 'spider': 8}

In [8]:
d

{'person': 2, 'cat': 4, 'spider': 8}

In [9]:
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
    

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [10]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [14]:
# sets
animals = {'cat', 'dog'}

In [16]:
animals

{'cat', 'dog'}

In [17]:
animals.add('human')

In [18]:
animals

{'cat', 'dog', 'human'}

In [19]:
len(animals)

3

In [22]:
for ids, objects in enumerate(animals):
    print('%d is in %s' % (ids, objects))

0 is in dog
1 is in human
2 is in cat


In [25]:
for ids, objects in enumerate(animals):
    print('%d:  %s' % (ids+1, objects))

1:  dog
2:  human
3:  cat


In [26]:
from math import sqrt
num = {int(sqrt(x)) for x in range(30)}
print(num)

{0, 1, 2, 3, 4, 5}


In [35]:
d = {(x, x + 1):x**2 for x in range(10)} 
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 4,
 (3, 4): 9,
 (4, 5): 16,
 (5, 6): 25,
 (6, 7): 36,
 (7, 8): 49,
 (8, 9): 64,
 (9, 10): 81}

In [36]:
t = (5,6)

In [37]:
print(d[t])

25


In [40]:
t = (7,8)

In [41]:
print(d[t])

49


In [46]:
# functions
def sign(x):
    if x>0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
    
for x in [1,-1,0]:
    print('%d : %s '%(x,sign(x)))
        

1 : positive 
-1 : negative 
0 : zero 


In [48]:
# functions optional arguments
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)
        
hello('Sadman')
hello('Soumik', loud=True) 

Hello, Sadman
HELLO, SOUMIK!
