Reductions

In [1]:
import numpy as np

In [2]:
x = np.arange(5)

In [3]:
sum(x)

10

In [7]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
x.sum(axis = 0)  # column wise summation

array([5, 7, 9])

In [9]:
x.sum(axis = 1)  # row-wise summation

array([ 6, 15])

In [11]:
x.min()

1

In [13]:
x.max()

6

In [14]:
x.argmin()  # index of minimum element

0

In [15]:
x.argmax()   #index of maximum element

5

Logical Operations

In [17]:
np.all([True, True, False, True])

False

In [18]:
np.any([True, True, False, True])

True

In [19]:
a = np.zeros(50)

In [20]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.any(a)

False