### Slicing and Indexing

In [1]:
import numpy as np

In [2]:
ar = np.diag([1,2,3])

In [3]:
ar

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [5]:
print(ar[2,2])

3


In [8]:
ar[2,2] = 5  # assigning new values to an index

In [9]:
print(ar[2,2])

5


In [4]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
ar[0:len(ar):2]   # start, end(excluding), step 

array([0, 2, 4, 6, 8])

In [12]:
ar = np.arange(20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
ar[15:] = 100   # from index 15 to the last element make everything 100
ar

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14, 100, 100, 100, 100, 100])

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])