In [2]:
import numpy as np

In [8]:
x = np.array([1,5,6,8,9,5])
y = np. array([[4,5,6],[7,8,4]])

In [9]:
x.mean()

5.666666666666667

In [10]:
np.median(x)

5.5

In [13]:
np.mean(y, axis=1)   # row-wise

array([5.        , 6.33333333])

In [16]:
np.median(y, axis=0)   # coloumn-wise

array([5.5, 6.5, 5. ])

In [17]:
y.std()

1.4907119849998596

In [18]:
x.std()

2.560381915956203

In [4]:
ab = np.arange(5)
ab

array([0, 1, 2, 3, 4])

In [6]:
ab.shape

(5,)